#
#  This is intended to set up Varnish to run under Docker Compose.
#  For swarm, use the file "swarm.yaml" instead.
#
volumes:
  certs:
    name: certs
    external: true

networks:
  # We'll run on this network, and other Compose projects
  # that want to run web services will, too.
  proxy:
    name: proxy
    external: true
    
services:

# Varnish and hitch will communicate over port 8443 over the proxy network
# 2023-03-27 Note the "enterprise" (not free) version of Varnish has TLS built in.
# I imagine eventually Hitch will be deprecated.

  # I listen for everything on port 443, using Let's Encrypt certificates
  # and then send everything over the PROXY connection to Varnish on port 8443
  hitch:
#    image: nginx:latest # Hacky way to test settings (won't keep crashing and restarting)
    image: hitch
    volumes:
      - ./etc/hitch.conf:/etc/hitch/hitch.conf:ro
      - certs:/etc/letsencrypt:ro
    ports:
      # Move to port 444 if you want to do testing on production server
      - "443:443"
    restart: always
    networks:
      proxy:
        aliases:
          - hitch

  # I need to have port 80 visible so that I can redirect traffic to TLS.
  # Everything else comes in from hitch.
  varnish:
    image: ghcr.io/clatsopcounty/varnish:latest
    volumes:
      - ./etc/default.bellman.vcl:/etc/varnish/default.vcl
    ports:
      - "80:80"
    tmpfs: "/var/lib/varnish/varnishd:rw,exec"
    restart: always
    networks:
      proxy:
        aliases:
          - varnish

