FROM certbot/dns-dnsmadeeasy

# I want the output to go to stdout but this does not work
RUN mkdir /var/log/letsencrypt && \
    ln -sf /dev/stdout /var/log/letsencrypt/letsencrypt.log

COPY dnsmadeeasy.ini /usr/local/lib/
RUN chmod 400 /usr/local/lib/dnsmadeeasy.ini

# This is run as a task, not a service, so it does not need a HEALTHCHECK
