FROM certbot/dns-cloudflare

# This makes output go to stdout but it's got DEBUG turned on.
# https://github.com/certbot/certbot/issues/3481
# so for now, skip it!
#RUN mkdir /var/log/letsencrypt && \
#    ln -sf /dev/stdout /var/log/letsencrypt/letsencrypt.log

COPY cloudflare.ini /usr/local/lib/
RUN chmod 600 /usr/local/lib/cloudflare.ini

