FROM certbot/dns-cloudflare

# I want the output to go to stdout but this does not work
RUN mkdir /var/log/letsencrypt && \
    ln -sf /dev/stdout /var/log/letsencrypt/letsencrypt.log

COPY cloudflare.ini /usr/local/lib/
RUN chmod 600 /usr/local/lib/cloudflare.ini

